import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Components

import TopBar from "./components/Topbar";
// import TripList from "./components/TripList";
import OverlayPanel from "./components/OverlayPanel";
// import DistanceForm from "./components/DistanceForm";
import MonthlySummaryCard from "./components/MonthlySummaryCard";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Trip Ledger",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="flex flex-col items-center justify-center">
          <TopBar />
          <div className="flex flex-row items-start justify-center w-full gap-4 p-4">
            <MonthlySummaryCard />
            <OverlayPanel />
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
